server:
  port: 8090

spring:
  application:
    name: Smart Park Application

  datasource:
    url: jdbc:h2:file:./db/data/smartparkdb
    driver-class-name: org.h2.Driver
    username: sa
    password: admin

  h2:
    console:
      enabled: true #Enable H2 web console
      path: /h2-console #Path http://localhost:8090/h2-console

  security:
    user.name: user
    user.password: admin12345

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Auto-creates tables based from Entity
    show-sql: true  # Show SQL queries in logs

jwt:
  expirationMs: 3600000